import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav">
          <h1>Pokemon Data</h1>
        </div>
        <div className="main-container">
          {children}
        </div>
        <footer>
          Alvaro Diaz - Funval 2023
        </footer>
      </body>
    </html>
  )
}
